create table cabhub (vcode number primary key, vehiclename varchar2(20), make varchar2(20), color varchar2(10), capacity number, charges number);
insert into cabhub values (100,'innova','toyota','white',7,15);
insert into cabhub values (102,'sx4','suzuki','blue',4,14);
insert into cabhub values (104,'c-class','mercedes','red',4,35);
insert into cabhub values (105,'a-star','suzuki','white',3,14);
insert into cabhub values (108,'indigo','tata','silver',3,12);
create table customer (code number primary key, cname varchar2(20), vcode number);
insert into customer values (1,'hemantsahu',101);
insert into customer values (2,'raj lal',108);
insert into customer values (3,'feroza shah',105);
insert into customer values (4,'ketan dhall',104);
select vehiclename from cabhub where color = 'white';
select vehiclename, capacity from cabhub order by capacity asc;
select max(charges) from cabhub;
select cname, vehiclename from customer, cabhub where customer.vcode = cabhub.vcode;
select count(distinct make) from cabhub;
select max(charges), min(charges) from cabhub;
select count(*), make from cabhub group by make;
select vehiclename from cabhub where capacity = 4;
